---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: sumanth230823/sumanthnewapp:dbimage
   ports:
     - "3306:3306"

 application:
   image: sumanth230823/sumanthnewapp:appimage
   container_name: containerapp
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
